<?php

namespace App\Modules\Cashbox\Enums;

enum CostTypesEnum: string
{
    case SUPPLIER_PAYMENT_OUTPUT = 'SUPPLIER_PAYMENT_OUTPUT';
    case CLIENT_PAYMENT_OUTPUT = 'CLIENT_PAYMENT_OUTPUT';
    case OTHER_PAYMENT_OUTPUT = 'OTHER_PAYMENT_OUTPUT';
    case COST_PAYMENT_OUTPUT = 'COST_PAYMENT_OUTPUT';
}
