name: Deploy to Dev Server

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to dev server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: main
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/main
            chmod +x deploy-backend.sh
            ./deploy-backend.shs
