name: Deploy to Server

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: main
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/main
            chmod +x deploy-backend.sh
            ./deploy-backend.sh
  migrate:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Migrate Database
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: main
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/main
            chmod +x migrate.sh
            ./migrate.sh
